version: "3"

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - MONGO_URL=mongodb://database:27017/mydatabase
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn test test.spec.js
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp
      - database

volumes:
  mongo_data:
