---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Change to webapp directory
        run: cd webapp

      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Lint Code
        run: yarn lint
        working-directory: ./webapp
