name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Lint Code
        run: yarn lint
        working-directory: ./webapp

      - name: Run Tests
        run: yarn test
        working-directory: ./webapp

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          tags: ademayari/webapp:latest
          push: false
